[package]
name = "libp2p-identity"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
mhash = { version = "*", features = ["generation", "validation", "sha2"] }
protobuf = "*"
ring = { path = "../ring", features = ["rsa_signing"] }
untrusted = "*"
